### ISSUE TITLE
Bugs in get_pos_proposal_indexes for mask loss

### ISSUE THREAD

**Issue by Devin147** [yinghdb/EmbedMask#10]
box_regression are not mutiplied by fpn_strides when get pos proposal indexes for mask loss
https://github.com/yinghdb/EmbedMask/blob/093348eface286f2fbe04cd6a08d79ea1f7c8ac3/fcos_core/modeling/rpn/embed_mask/loss.py#L227

**Comment by yinghdb** [comment]
You are right! This is a mistake. The bug is fixed as following:

https://github.com/yinghdb/EmbedMask/blob/3b4d9fb4e0b6112dc501708184ff684dfb45f3f0/fcos_core/modeling/rpn/embed_mask/loss.py#L232

Thanks a lot for your reminder. And the new models will be updated later.
