### ISSUE TITLE
Speed performance

### ISSUE THREAD

**Issue by Epiphqny** [yinghdb/EmbedMask#12]
Thanks for your code, after running the Speed Testing code, the fps is 8.19 for embed_mask_R101_ms_3x.pth, but in the paper the speed is 13.7 fps, what does the fps in the paper refer to ?  why is there a difference?

**Comment by yinghdb** [comment]
@Epiphqny 
What kind of GPU do you use?

**Comment by Epiphqny** [comment]
> @Epiphqny
> What kind of GPU do you use?

Tesla V100
