### ISSUE TITLE
Positive samples for proposal embedding and margin

### ISSUE THREAD

**Issue by JyunYuLai** [yinghdb/EmbedMask#17]
Hi @yinghdb  ,

Thank you for your wonderful work.
As the title, there is a difference between the paper and implementation in sampling.
In paper, you use samples that iou(pred, target) > 0.5 .
But in the latest implementation, use just use "one" best samples for each gt box.
What is the impact on performance after this change?
Thank you.

**Comment by yinghdb** [comment]
This is mainly a experimental conclusion, that using "only the best sample" has the same or a little better performance than using "multi samples". Also it avoids the need for adjusting the parameters, like iou threshold.

**Comment by JyunYuLai** [comment]
Thank you for quick reply and help.
