### ISSUE TITLE
FCOS structure

### ISSUE THREAD

**Issue by trungpham2606** [yinghdb/EmbedMask#3]
@yinghdb Which FCOS structure are you using ?

**Comment by yinghdb** [comment]
What is the meaning of 'FCOS structure' ?

**Comment by trungpham2606** [comment]
@yinghdb I saw that in FCOS implementation, they used deformable convolutions in some config files, so I have a question that in your EmbedMask, did you train with deformable convolutions or not ?

**Comment by yinghdb** [comment]
I have not used deformable convolutions. In fact, for the configuration to the detection part of EmbedMask,  I use the settings from the 'fcos_imprv_R_50_FPN_1x.yaml' as default.
