### ISSUE TITLE
unreachable gradient

### ISSUE THREAD

**Issue by afantideng** [yinghdb/EmbedMask#7]
@yinghdb 
I simply modify the class number of embed_mask_R50_1x.yaml from 81 to 2 to train coco-persons (I use the person keypoints JSON files directly since they also contain segment annotations ). However, where training in distributed form，an unreachable gradient problem occurred, I wonder if there's some potential factors to trigger this problem.

Here is the information in details:

`Traceback (most recent call last):
  File "tools/train_net.py", line 185, in <module>
    main()
  File "tools/train_net.py", line 178, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 84, in train
    cfg
  File "./fcos_core/engine/trainer.py", line 80, in do_train
    losses.backward()
  File "/root/env/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/env/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/root/env/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/root/env/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]`

**Comment by yinghdb** [comment]
Your problem is like what is described in [here](https://github.com/NVIDIA/apex/issues/265#issuecomment-485299402). According to the first answer, I add a meaningless loss to avoid gradients missing, and I have pushed the new code to the github. You can try if it works with the newest code.

**Comment by afantideng** [comment]
@yinghdb Thanks for your reply, it works!  So does it mean that switching the cls_num of the network would make some part of the proposal_embed, proposal_margin or pixel_embed not included in loss computation ? (When I train the network using your original configs, this problem would disappear.)

**Comment by yinghdb** [comment]
@afantideng I think it is related to the dataset or batch size. We use FPN architecture in the network, so objects with different sizes will be processed at different feature levels. When there is no object that should be processed on a certain feature level, the gradient missing will occur (cause proposal_embed and proposal_margin on that level will not be used for computing loss). And this case will often appear when the batch size is small or the size variance of objects in the dataset is small, which I think should be careful about when changing datasets.

**Comment by afantideng** [comment]
@yinghdb Thanks a lot!

**Comment by shoutOutYangJie** [comment]
Very responsible.
